version: '3.7'
services:
  service-1:
    image: suban92/service-1 #python-front-and-back_service-1
    deploy:
      replicas: 2
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service-4:
    #image: python-front-and-back_service-4
    image: suban92/service-4
    deploy:
      replicas: 2
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
  service-2:
    #image: python-front-and-back_service-2
    image: suban92/service-2
    deploy:
      replicas: 2
    ports:
    - target: 5001
     
      published: 5001
      protocol: tcp
  service-3:
    #image: python-front-and-back_service-3
    image: suban92/service-3
    deploy:
      replicas: 2
    ports:
    - target: 5002
      published: 5002
      protocol: tcp